[package]
name = "g-cli"
version = "3.0.0"
authors = ["James McNally <james@wiresmithtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.15"
log = "0.4"
simple_logger = "1.11"