
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  rust-style:
    name: Check Style
    runs-on: ubuntu-latest
    working-directory: rust-proxy
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build-cli:
    name: Test & Build on ${{ matrix.os }}
    needs: [style]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest


    runs-on: ${{ matrix.os }}

    working-directory: rust-proxy

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Upload EXE
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: Exe_${{ matrix.os }}
          # A file, directory or wildcard pattern that describes what to upload
          path: target/release/g-cli.exe
          if-no-files-found: error

        
  build-lv:
  
    runs-on: labview
    needs: build-cli
    
    steps:
    
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: true

          
      - name: Get x64 EXE for Integration Test
        uses: actions/download-artifact@v2.1.0
        with:
          # Artifact name
          name: Exe_windows-latest
          # Destination path
          path: Integration Tests
    
      - name: LabVIEW Dependencies
        run: labview-cli -v "C:\Users\Public\Documents\National Instruments\LV-CLI Common Steps\steps\vipcApply.vi" -- "${{github.workspace}}\LabVIEW Source\Dependencies\G CLI Dev Dependencies.vipc" 2011
     
     #unit tests disabled due to lack of reporting support in lv2011. To be enabled when min LV version is bumped.
     # - name: Unit Tests
     #   run: labview-cli -v "C:\Users\Public\Documents\National Instruments\LV-CLI Common Steps\steps\run-vi-tester.vi" -- "LabVIEW Source\G-CLI.lvproj" "lv-results.xml" "${{github.workspace}}" 
     
      - name: Integration Tests
        working-directory: "Integration Tests"
        run: |
          dir
          .\run_integration_tests.bat .\
     
     #note the direct call as the build fails if the files are loaded.
      - name: LabVIEW Build
        run: |
          labview-cli -v --kill "C:\Users\Public\Documents\National Instruments\LV-CLI Common Steps\steps\setVipBuildNumber.vi" -- "LabVIEW Source\G CLI.vipb" "${{github.workspace}}" ${{github.run_number}}
          New-Item -ItemType Directory -Force -Path Builds
          cmd /c """C:\Program Files `(x86`)\National Instruments\LabVIEW 2011\LabVIEW.exe"" ""C:\Users\Public\Documents\National Instruments\LV-CLI Common Steps\steps\vipbBuild-nocli.vi"" -- ""LabVIEW Source\G CLI.vipb"" Builds  ""${{github.workspace}}"""
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
         name: vipackage
         path: Builds/**.vip
         if-no-files-found: error


